[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:27 test_Orange_Hrm_Login_001 is started
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:31 Opening the Browser
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:34 test_Orange_Hrm_Login_001 is Verified
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:35 test_Orange_Hrm_Login_001 is passed,user is landed on correct url
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:37 Taking The ScreenShot
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:46 Closing the browser
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:48 test_Orange_Hrm_Login_001 is Completed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001452E20DDD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4896ca333da11db6416dd4a42121667
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001452DF55CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4896ca333da11db6416dd4a42121667
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001452E20F390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d4896ca333da11db6416dd4a42121667